# Logo paths for menu selection page and team pages
logos = {'Major League Baseball': 'images/mlb_logo.png',
         'Arizona Diamondbacks': 'images/ari_logo.png', 
         'Athletics': 'images/ath_logo.png', 
         'Atlanta Braves': 'images/atl_logo.png', 
         'Baltimore Orioles': 'images/bal_logo.png',
         'Boston Red Sox': 'images/bos_logo.png',
         'Chicago Cubs': 'images/chc_logo.png',
         'Chicago White Sox': 'images/chi_logo.png',
         'Cincinnati Reds': 'images/cin_logo.png',
         'Cleveland Guardians': 'images/cle_logo.png',
         'Colorado Rockies': 'images/col_logo.png',
         'Detroit Tigers': 'images/det_logo.png',
         'Houston Astros': 'images/hou_logo.png',
         'Kansas City Royals': 'images/kcr_logo.png',
         'Los Angeles Angels': 'images/laa_logo.png',
         'Los Angeles Dodgers': 'images/lad_logo.png',
         'Miami Marlins': 'images/mia_logo.png',
         'Milwaukee Brewers': 'images/mil_logo.png',
         'Minnesota Twins': 'images/min_logo.png',
         'New York Mets': 'images/nym_logo.png',
         'New York Yankees': 'images/nyy_logo.png',
         'Philadelphia Phillies': 'images/phi_logo.png',
         'Pittsburgh Pirates': 'images/pit_logo.png',
         'San Diego Padres': 'images/sdp_logo.png',
         'San Francisco Giants': 'images/sfg_logo.png',
         'Seattle Mariners': 'images/sea_logo.png',
         'St. Louis Cardinals': 'images/stl_logo.png',
         'Tampa Bay Rays': 'images/tbr_logo.png',
         'Texas Rangers': 'images/tex_logo.png',
         'Toronto Blue Jays': 'images/tor_logo.png',
         'Washington Nationals': 'images/wsh_logo.png'}