# Logo paths for menu selection page and team pages
mlb_logo = ['Major League Baseball', 'images/mlb_logo.png']
ari_logo = ['Arizona Diamondbacks', 'images/ari_logo.png']
atl_logo = ['Atlanta Braves', 'images/atl_logo.png']
bal_logo = ['Baltimore Orioles', 'images/bal_logo.png']
bos_logo = ['Boston Red Sox', 'images/bos_logo.png']
chc_logo = ['Chicago Cubs', 'images/chc_logo.png']
cws_logo = ['Chicago White Sox', 'images/cws_logo.png']
cin_logo = ['Cincinnati Reds', 'images/cin_logo.png']
cle_logo = ['Cleveland Guardians', 'images/cle_logo.png']
col_logo = ['Colorado Rockies', 'images/col_logo.png']
det_logo = ['Detroit Tigers', 'images/det_logo.png']
hou_logo = ['Houston Astros', 'images/hou_logo.png']
kcr_logo = ['Kansas City Royals', 'images/kcr_logo.png']
laa_logo = ['Los Angeles Angels', 'images/laa_logo.png']
lad_logo = ['Los Angeles Dodgers', 'images/lad_logo.png']
mia_logo = ['Miami Marlins', 'images/mia_logo.png']
mil_logo = ['Milwaukee Brewers', 'images/mil_logo.png']
min_logo = ['Minnesota Twins', 'images/min_logo.png']
nym_logo = ['New York Mets', 'images/nym_logo.png']
nyy_logo = ['New York Yankees', 'images/nyy_logo.png']
oak_logo = ['Oakland Athletics', 'images/oak_logo.png']
phi_logo = ['Philadelphia Phillies', 'images/phi_logo.png']
pit_logo = ['Pittsburgh Pirates', 'images/pit_logo.png']
sdp_logo = ['San Diego Padres', 'images/sdp_logo.png']
sfg_logo = ['San Francisco Giants', 'images/sfg_logo.png']
sea_logo = ['Seattle Mariners', 'images/sea_logo.png']
stl_logo = ['St. Louis Cardinals', 'images/stl_logo.png']
tbr_logo = ['Tampa Bay Rays', 'images/tbr_logo.png']
tex_logo = ['Texas Rangers', 'images/tex_logo.png']
tor_logo = ['Toronto Blue Jays', 'images/tor_logo.png']
wsh_logo = ['Washington Nationals', 'images/wsh_logo.png']

ari_tplogo = ['Arizona Diamondbacks', 'images/ari_tplogo.png']
atl_tplogo = ['Atlanta Braves', 'images/atl_tplogo.png']
bal_tplogo = ['Baltimore Orioles', 'images/bal_tplogo.png']
bos_tplogo = ['Boston Red Sox', 'images/bos_tplogo.png']
chc_tplogo = ['Chicago Cubs', 'images/chc_tplogo.png']
cws_tplogo = ['Chicago White Sox', 'images/cws_tplogo.png']
cin_tplogo = ['Cincinnati Reds', 'images/cin_tplogo.png']
cle_tplogo = ['Cleveland Guardians', 'images/cle_tplogo.png']
col_tplogo = ['Colorado Rockies', 'images/col_tplogo.png']
det_tplogo = ['Detroit Tigers', 'images/det_tplogo.png']
hou_tplogo = ['Houston Astros', 'images/hou_tplogo.png']
kcr_tplogo = ['Kansas City Royals', 'images/kcr_tplogo.png']
laa_tplogo = ['Los Angeles Angels', 'images/laa_tplogo.png']
lad_tplogo = ['Los Angeles Dodgers', 'images/lad_tplogo.png']
mia_tplogo = ['Miami Marlins', 'images/mia_tplogo.png']
mil_tplogo = ['Milwaukee Brewers', 'images/mil_tplogo.png']
min_tplogo = ['Minnesota Twins', 'images/min_tplogo.png']
nym_tplogo = ['New York Mets', 'images/nym_tplogo.png']
nyy_tplogo = ['New York Yankees', 'images/nyy_tplogo.png']
oak_tplogo = ['Oakland Athletics', 'images/oak_tplogo.png']
phi_tplogo = ['Philadelphia Phillies', 'images/phi_tplogo.png']
pit_tplogo = ['Pittsburgh Pirates', 'images/pit_tplogo.png']
sdp_tplogo = ['San Diego Padres', 'images/sdp_tplogo.png']
sfg_tplogo = ['San Francisco Giants', 'images/sfg_tplogo.png']
sea_tplogo = ['Seattle Mariners', 'images/sea_tplogo.png']
stl_tplogo = ['St. Louis Cardinals', 'images/stl_tplogo.png']
tbr_tplogo = ['Tampa Bay Rays', 'images/tbr_tplogo.png']
tex_tplogo = ['Texas Rangers', 'images/tex_tplogo.png']
tor_tplogo = ['Toronto Blue Jays', 'images/tor_tplogo.png']
wsh_tplogo = ['Washington Nationals', 'images/wsh_tplogo.png']

def get_logos():
    return [mlb_logo, 
            ari_logo, atl_logo, bal_logo, bos_logo, chc_logo, cws_logo, cin_logo, cle_logo, col_logo, det_logo, hou_logo, kcr_logo, laa_logo, lad_logo, mia_logo, 
            mil_logo, min_logo, nym_logo, nyy_logo, oak_logo, phi_logo, pit_logo, sdp_logo, sfg_logo, sea_logo, stl_logo, tbr_logo, tex_logo, tor_logo, wsh_logo]

def get_tp_logos():
    return [ari_tplogo, atl_tplogo, bal_tplogo, bos_tplogo, chc_tplogo, cws_tplogo, cin_tplogo, cle_tplogo, col_tplogo, det_tplogo, hou_tplogo, kcr_tplogo, laa_tplogo, lad_tplogo, mia_tplogo, 
            mil_tplogo, min_tplogo, nym_tplogo, nyy_tplogo, oak_tplogo, phi_tplogo, pit_tplogo, sdp_tplogo, sfg_tplogo, sea_tplogo, stl_tplogo, tbr_tplogo, tex_tplogo, tor_tplogo, wsh_tplogo]